"""secondary_migration

Revision ID: 033fce2ffaeb
Revises: c32520ceb0dc
Create Date: 2024-10-18 19:46:03.739012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033fce2ffaeb'
down_revision: Union[str, None] = 'c32520ceb0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idenpotency_keys_id', table_name='idenpotency_keys')
    op.drop_table('idenpotency_keys')
    op.add_column('order', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'order', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'idempotency_key')
    op.create_table('idenpotency_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idenpotency_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='idenpotency_keys_pkey')
    )
    op.create_index('ix_idenpotency_keys_id', 'idenpotency_keys', ['id'], unique=False)
    # ### end Alembic commands ###
