"""Add relationship column  in orders

Revision ID: 03d43e50d65f
Revises: 26dbb31fb225
Create Date: 2024-10-05 16:35:53.115604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d43e50d65f'
down_revision: Union[str, None] = '26dbb31fb225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
