"""third_migration

Revision ID: 0cc21e3e21e2
Revises: 915ab7bcdd9c
Create Date: 2024-10-26 13:22:14.375335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cc21e3e21e2'
down_revision: Union[str, None] = '915ab7bcdd9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('payload', sa.JSON(), nullable=False))
    op.drop_column('outbox', 'paylod')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('paylod', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('outbox', 'payload')
    # ### end Alembic commands ###
