services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:v21.11.11
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 29092:29092
  db:
    image: postgres:15
    container_name: order_db
    env_file:
      - .env-nov-dev
    ports:
      - 5433:5433
    command : ["-p", "5433"]
  order:
    image: order_image
    build:
      context: .
    container_name: order_app
    env_file:
      - .env-nov-dev
    depends_on:
      - db
    command: ["/order/docker/app.sh"]
    ports:
      - 7777:8000

